safe:
  - "gitpython"
  - "jinja2"
  - "markdown2"
  - "more-itertools"
  - "pluggy"
  - "python-dateutil"
  - "python-frontmatter"
  - "python-slugify"
  - "render-engine-parser"
  - "render-engine-markdown"
  - "rich"
  - "typer"
  - "watchdog"