# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the pypi registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    # Group dependencies by type production, development, and render-engine
    # This will create a single PR for each group
    groups:
      # [project.dependencies] and [project.optional-dependencies].cli, needs to be confirmed
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
      render-engine:
        patterns:
          - "render-engine-*"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
