site_name: Render Engine
site_url: https://render-engine.readthedocs.io
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/create-app.md
    - getting-started/layout.md
    - getting-started/creating-a-page.md
    - getting-started/creating-a-collection.md
  - Components:
    - Page: page.md
    - Collection:
      - Collection: collection.md
      - Archive: archive.md
      - RSS Feed: feeds.md
    - Site:
      - Site: site.md
      - Plugins: hookspecs.md
  - Extending Render Engine:
    - Built-in Plugins: plugins.md
    - Plugins: plugins.md
markdown_extensions:
  - toc
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

watch:
  - ../src/render_engine
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [../src]
        options:
          show_source: false
          show_root_full_path: false
          show_category_heading: true
