site_name: Render Engine
site_url: https://render-engine.readthedocs.io
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/getting-started.md
    - getting-started/installation.md
    - getting-started/creating-your-app.md
    - getting-started/layout.md
    - getting-started/creating-a-page.md
    - getting-started/creating-a-collection.md
    - getting-started/building-your-site.md
  - Contributing:
    - contributing/CODE_OF_CONDUCT.md
    - contributing/environment_setup.md
    - contributing/CONTRIBUTING.md
  - Components:
    - Page Objects: page.md
    - Collection:
      - Collection: collection.md
      - Custom Collection: custom_collections.md
      - Archive: archive.md
      - RSS Feed: feeds.md
    - Site:
      - Site: site.md
  - Extending Render Engine:
    - Plugins: plugins.md
  - Parsers: parsers.md
  - CLI: cli.md
  - Templates and Themes:
    - Templates: templates.md
    - ThemeManager: theme_management.md

markdown_extensions:
  - toc
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
watch:
  - ../src/render_engine
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [../src]
        options:
          show_source: false
          show_root_full_path: false
          show_category_heading: true
