name: Check Dev Container

on:
  push:
    branches: [ main ]
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer-ci.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer-ci.yaml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install -g @devcontainers/cli
      - run: devcontainer build --config ./.devcontainer/devcontainer.json --workspace-folder "$(pwd)"
