name: PyTest
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "requirements.txt"

permissions:
  contents: read

jobs:
  gen-coverage-badge:
    name: Generate Coverage Badge
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: "3.14"
          enable-cache: true

      - name: run coverage and generate cov-report
        run: |
          uv run --dev pytest --cov-report xml
      - name: genbadge coverage
        run: |
          uvx --with "genbadge[coverage]" genbadge coverage -i coverage.xml
      - name: Commit Badge
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: Update coverage badge [skip ci]
          file_pattern: coverage.svg

  test-against-python-matrix:
    name: Test on all supported Python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.14 is not run here because it is for the latest OK check so it would be redundant.
        python-version: ["3.11", "3.12", "3.13", "3.15"]
      fail-fast: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true # caching dependencies
      - name: Run tests
        run: |
          uv run --dev --python ${{ matrix.python-version }} pytest tests

  test-against-latest-os:
    # Always run against the latest version on both Windows, Linux, MacOS
    name: Test against latest OS
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: "3.14"
          enable-cache: true # caching dependencies
      - name: run tests
        run: uv run --dev --python 3.14 pytest tests
