name: "Run TODO to Issue"
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v6"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          INSERT_ISSUE_URLS: "true"
          CLOSES_ISSUE: "true"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
